name: example
description: "Monitor HTTP example app."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  http_parser: ^4.1.0
  monitor: ^1.3.0
  monitor_http:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
